version: '3'
services:
  opentsdb:
    image: driftedhawk49/opentsdb-docker:latest
    container_name: opentimeseriesdb
    environment:
      AUTH_USER: admin
      AUTH_KEY: admin123 
    ports:
      - "31005:80"
